name: flutter_pw_validator
description: Flutter Pw Validator package helps you to validate sign in user-entered password with your rules.
version: 1.7.1

environment:
  sdk: '>=2.17.0 <3.19.1'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: